# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 10, 13, 19, 33, 994178, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
